/**
 * RestoPanel · Mock data — Customers (CRM 360°)
 * Numbers are kept consistent: e.g. "Marta Ruiz" → 14 visits.
 */

export interface MockCustomer {
  id: string;
  name: string;
  email: string;
  phone: string;
  visits: number;
  avgTicket: number;
  totalSpent: number;
  tags: string[]; // "VIP" | "Frecuente" | "Cumpleaños" | "Alergia" | "Especial"
  allergens: string[];
  lastVisit: string; // ISO date
  birthday: string;  // MM-DD
  vip: boolean;
}

export const MOCK_CUSTOMERS: MockCustomer[] = [
  {
    id: "C-001",
    name: "Marta Ruiz",
    email: "marta.ruiz@gmail.com",
    phone: "+34 611 223 314",
    visits: 14,
    avgTicket: 92,
    totalSpent: 1288,
    tags: ["VIP", "Frecuente", "Cumpleaños"],
    allergens: ["Frutos secos"],
    lastVisit: "2025-11-18",
    birthday: "11-22",
    vip: true,
  },
  {
    id: "C-002",
    name: "Javier Soto",
    email: "javier.soto@outlook.com",
    phone: "+34 622 880 110",
    visits: 9,
    avgTicket: 68,
    totalSpent: 612,
    tags: ["Frecuente"],
    allergens: [],
    lastVisit: "2025-11-12",
    birthday: "03-14",
    vip: false,
  },
  {
    id: "C-003",
    name: "Lucía Ferrer",
    email: "lucia.ferrer@gmail.com",
    phone: "+34 633 441 552",
    visits: 6,
    avgTicket: 84,
    totalSpent: 504,
    tags: ["Frecuente", "Alergia"],
    allergens: ["Gluten"],
    lastVisit: "2025-11-20",
    birthday: "07-02",
    vip: false,
  },
  {
    id: "C-004",
    name: "Andrés Pardo",
    email: "andres.pardo@yahoo.es",
    phone: "+34 644 552 998",
    visits: 3,
    avgTicket: 56,
    totalSpent: 168,
    tags: [],
    allergens: ["Lactosa"],
    lastVisit: "2025-10-29",
    birthday: "01-19",
    vip: false,
  },
  {
    id: "C-005",
    name: "Carmen Velasco",
    email: "carmen.velasco@gmail.com",
    phone: "+34 655 220 117",
    visits: 22,
    avgTicket: 110,
    totalSpent: 2420,
    tags: ["VIP", "Frecuente"],
    allergens: ["Marisco"],
    lastVisit: "2025-11-21",
    birthday: "11-25",
    vip: true,
  },
  {
    id: "C-006",
    name: "Diego Marín",
    email: "diego.marin@protonmail.com",
    phone: "+34 666 110 882",
    visits: 4,
    avgTicket: 73,
    totalSpent: 292,
    tags: [],
    allergens: [],
    lastVisit: "2025-11-04",
    birthday: "05-30",
    vip: false,
  },
  {
    id: "C-007",
    name: "Nuria Cano",
    email: "nuria.cano@gmail.com",
    phone: "+34 677 332 110",
    visits: 11,
    avgTicket: 89,
    totalSpent: 979,
    tags: ["Frecuente", "Cumpleaños"],
    allergens: [],
    lastVisit: "2025-11-19",
    birthday: "11-28",
    vip: false,
  },
  {
    id: "C-008",
    name: "Pablo Hidalgo",
    email: "pablo.hidalgo@gmail.com",
    phone: "+34 688 443 220",
    visits: 18,
    avgTicket: 95,
    totalSpent: 1710,
    tags: ["VIP", "Frecuente"],
    allergens: ["Apio"],
    lastVisit: "2025-11-22",
    birthday: "02-11",
    vip: true,
  },
  {
    id: "C-009",
    name: "Sofía Montero",
    email: "sofia.montero@outlook.com",
    phone: "+34 699 554 003",
    visits: 5,
    avgTicket: 62,
    totalSpent: 310,
    tags: [],
    allergens: ["Huevo"],
    lastVisit: "2025-11-08",
    birthday: "09-17",
    vip: false,
  },
  {
    id: "C-010",
    name: "Mateo Rivas",
    email: "mateo.rivas@gmail.com",
    phone: "+34 610 665 224",
    visits: 7,
    avgTicket: 78,
    totalSpent: 546,
    tags: ["Frecuente"],
    allergens: [],
    lastVisit: "2025-11-15",
    birthday: "08-23",
    vip: false,
  },
  {
    id: "C-011",
    name: "Elena Carrasco",
    email: "elena.carrasco@gmail.com",
    phone: "+34 621 776 008",
    visits: 16,
    avgTicket: 102,
    totalSpent: 1632,
    tags: ["VIP", "Frecuente", "Cumpleaños"],
    allergens: ["Frutos secos", "Marisco"],
    lastVisit: "2025-11-21",
    birthday: "12-01",
    vip: true,
  },
  {
    id: "C-012",
    name: "Hugo Bermúdez",
    email: "hugo.bermudez@yahoo.es",
    phone: "+34 632 887 559",
    visits: 2,
    avgTicket: 54,
    totalSpent: 108,
    tags: [],
    allergens: [],
    lastVisit: "2025-10-25",
    birthday: "04-09",
    vip: false,
  },
];
